variables:
  APP_NAME: "th2-infra-mgr"
  MAJOR_VERSION: "0"
  MINOR_VERSION: "13"
  MAINTENANCE_VERSION: "1"
  DOCKER_PUBLISH_ENABLED: "true"

include:
  - project: "vivarium/th2/pipelines"
    ref: master
    file: "/.gitlab-ci-java.yml"
