variables:
  APP_NAME: "th2-infra-mgr"
  MAJOR_VERSION: "0"
  MINOR_VERSION: "12"
  MAINTENANCE_VERSION: "2"
  DOCKER_PUBLISH_ENABLED: "true"

include:
  - project: "vivarium/th2/pipelines"
    ref: master
    file: "/.gitlab-ci-java.yml"
